// -*- IDL -*-

// $Id: ImR_Activator.idl 94989 2011-11-08 19:13:08Z johnnyw $

#include "tao/ImR_Client/ImplRepo.pidl"

module ImplementationRepository
{
  interface Activator
  {
    /// Tells the activator to launch a server with the given information.
    void start_server(in string name, in string cmdline,
      in string dir, in EnvironmentList env) raises(CannotActivate);

    oneway void shutdown();
  };
};

