// $Id: Collocated_Base.idl 95875 2012-06-13 05:54:39Z johnnyw $

#ifndef COLLACATED_BASE_
#define COLLACATED_BASE_

#pragma ndds typesupport "Base/Collocated_BaseSupport.h"
#pragma opendds typesupport "Base/Collocated_BaseTypeSupportImpl.h"

#pragma DCPS_DATA_TYPE "CoPubSub::Test_msg"

module CoPubSub {
  struct Test_msg {
    string hello;
    long msgId;
  };

#if defined DDS4CCM_NEEDS_SEQUENCES_DEFINED
typedef sequence <Test_msg> Test_msgSeq;
#endif
};


#endif // COLLACATED_BASE_

