//$Id: Receiver.idl 68081 2005-09-01 19:26:35Z wotte $:

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "../Minimum_Base/Minimum_Base.idl"

module Minimum
{
  component Receiver
  {
  };

  home ReceiverHome manages Receiver
  {
  };
};
#endif /*RECEIVER_IDL*/
