// $Id: Diamond.idl 26568 1999-07-14 07:32:40Z nanbor $

module Diamond
{
  interface Top
    {
      string shape ();
    };

  interface Left : Top
    {
      string color ();
    };

  interface Right : Top
    {
      long width ();
    };

  interface Buttom : Left, Right
    {
      string name ();
    };
};
