//
// $Id: test.idl 24758 1999-06-18 16:58:09Z coryan $
//

interface Simple_Server
{
  long test_method (in long x);

  exception Failure {};
  long test_raise (in long x) raises (Failure);

  oneway void shutdown ();
};
