// $Id: test.idl 81526 2008-04-29 15:35:29Z smcqueen $

// Oh ho, oh ho, what are we gonna do?
union CityBlue
  switch (unsigned long long)
{
  case 1:
    long ucb_long;
  default:
    short ucb_short;
};

// Power, passion, plays a double hand
union CityMan
  switch (long long)
{
  case 1:
    long ucm_long;
  default:
    short ucm_short;
};

