// $Id: Quoter_Producer.idl 93359 2011-02-11 11:33:12Z mcorino $

#ifndef QUOTER_PRODUCER_IDL
#define QUOTER_PRODUCER_IDL

#include <Components.idl>

#include "Base/Quoter.idl"

module Quoter
{
  component Producer
  {
    /// Provides
    provides StockManager my_quoter;
  };
};
#endif
