
// -*- C++ -*-
// $Id: Version.h 97359 2013-10-03 07:49:34Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define TAO_MAJOR_VERSION 2
#define TAO_MINOR_VERSION 2
#define TAO_BETA_VERSION 2
#define TAO_VERSION "2.2.2"
