
// -*- C++ -*-
// $Id: Version.h 97295 2013-08-16 06:57:50Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define TAO_MAJOR_VERSION 2
#define TAO_MINOR_VERSION 2
#define TAO_BETA_VERSION 1
#define TAO_VERSION "2.2.1"
