
// -*- C++ -*-
// $Id: Version.h 97118 2013-05-13 06:53:59Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define TAO_MAJOR_VERSION 2
#define TAO_MINOR_VERSION 1
#define TAO_BETA_VERSION 9
#define TAO_VERSION "2.1.9"
