//
// $Id: test.idl 41673 2001-09-18 00:06:07Z irfan $
//

interface Test
{
  void test_method (in boolean client_propagated,
                    in short client_priority);

  oneway void shutdown ();
};
