
// -*- C++ -*-
// $Id: Version.h 96185 2012-10-12 09:21:55Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define CIAO_MAJOR_VERSION 1
#define CIAO_MINOR_VERSION 1
#define CIAO_BETA_VERSION 5
#define CIAO_VERSION "1.1.5"
