
// -*- C++ -*-
// $Id: Version.h 96250 2012-11-12 08:36:04Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define CIAO_MAJOR_VERSION 1
#define CIAO_MINOR_VERSION 1
#define CIAO_BETA_VERSION 6
#define CIAO_VERSION "1.1.6"
