
// -*- C++ -*-
// $Id: Version.h 97118 2013-05-13 06:53:59Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define CIAO_MAJOR_VERSION 1
#define CIAO_MINOR_VERSION 1
#define CIAO_BETA_VERSION 9
#define CIAO_VERSION "1.1.9"
