// $Id: Bug_3819_Regression.idl 88815 2010-02-03 09:54:02Z vzykov $

module orange {
    module apple {
        valuetype Foo;
        valuetype Foo;

        component Bar;
        component Bar;
    };
};
