// $Id: typeprefix.idl 73380 2006-07-03 10:23:43Z jwillemsen $

// Test a construct with typeprefix which failed when TAO_IDL was build
// with Intel C++ or Sun C++

module A
{
  typeprefix A "TAO";
  interface B {};
  interface C{
    void op (in B a);
  };
};
/*
module A
{
  typeprefix A "TAO";
  interface B{};
};*/

