//
// $Id: test.idl 96986 2013-04-11 16:39:42Z mesnier_p $
//

interface test
{
  long method (in long client_id,
               in long iteration,
               out long thread_count);

  oneway void shutdown ();
};
