// $Id: Hello_Receiver.idl 96161 2012-09-27 09:30:10Z johnnyw $

#ifndef HELLO_RECEIVER_IDL
#define HELLO_RECEIVER_IDL

#include <Components.idl>

#include "Base/Hello.idl"

module Hello
{
  component Receiver
  {
    /// Provides
    provides MyFoo do_my_foo;
  };
};
#endif
