// $Id: incorrect_consumes.idl 89824 2010-04-09 11:41:21Z johnnyw $

#include <Components.idl>

eventtype foo_event
{
};

interface A
{
  long do_something ();
};

connector B
{
  provides A x;
  uses A y;
  consumes foo_event c_foo;
};
