// $Id: Deployment_InvalidProperty.idl 90214 2010-05-21 13:59:45Z wotte $

#ifndef DEPLOYMENT_INVALIDPROPERTY_IDL
#define DEPLOYMENT_INVALIDPROPERTY_IDL

module Deployment {
  exception InvalidProperty {
    string name;
    string reason;
  };
};

#endif
