#!/bin/bash -x
# $Id: make-client-keys 96105 2012-08-28 09:34:54Z johnnyw $

openssl req -new -x509 -days 3650 -nodes -newkey rsa:1024 \
    -out server-cert.pem -keyout server-key.pem \
    -subj "/C=US/ST=MO/L=St. Louis/O=OCI/CN=server"

cat server-cert.pem >>server-key.pem
cat server-cert.pem >ca.pem
        
openssl req -new -x509 -days 3650 -nodes -newkey rsa:1024 \
    -out client-cert.pem -keyout client-key.pem \
    -subj "/C=US/ST=MO/L=St. Louis/O=OCI/CN=client"

cat client-cert.pem >>client-key.pem
cat client-cert.pem >>ca.pem
        
