//
// $Id: Sender.idl 95050 2011-11-16 22:46:23Z fields_t $
//
#include "Receiver.idl"

interface Sender
{

  exception Table_Full {};

  /// Receive the Receiver object and return a id for the object.
  long receiver_object (in Receiver recv)
    raises (Table_Full);
};
