// $Id: Diamond.idl 80286 2007-12-17 16:40:55Z mitza $

module Diamond
{
  interface Top
    {
      string shape ();
    };

  interface Left : Top
    {
      string color ();
    };

  interface Right : Top
    {
      long width ();
    };

  interface Buttom : Left, Right
    {
      string name ();
    };
};
