
// -*- C++ -*-
// $Id: Version.h 97359 2013-10-03 07:49:34Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define ACE_MAJOR_VERSION 6
#define ACE_MINOR_VERSION 2
#define ACE_BETA_VERSION 2
#define ACE_VERSION "6.2.2"
