
// -*- C++ -*-
// $Id: Version.h 97168 2013-05-27 08:11:03Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define ACE_MAJOR_VERSION 6
#define ACE_MINOR_VERSION 2
#define ACE_BETA_VERSION 0
#define ACE_VERSION "6.2.0"
