
// -*- C++ -*-
// $Id: Version.h 97118 2013-05-13 06:53:59Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define ACE_MAJOR_VERSION 6
#define ACE_MINOR_VERSION 1
#define ACE_BETA_VERSION 9
#define ACE_VERSION "6.1.9"
