// $Id: CSL_QoSTest_Receiver.idl 95883 2012-06-13 18:45:09Z johnnyw $

/**
 * @file
 * @author Marijke Hengstmengel (mhengstmengel@remedy.nl)
 */

#ifndef RECEIVER_IDL
#define RECEIVER_IDL

#include "Connector/CSL_QoSTest_Connector.idl"

module CSL_QoSTest
{
  component Receiver
  {
    port CSLQoSConnector::DDS_Listen info_out;
    provides CCM_DDS::ConnectorStatusListener info_out_connector_status;
   };
};

#endif
