//$Id: MIF_Scheduling.idl 65765 2005-05-02 18:38:58Z jwillemsen $

#include "tao/RTScheduling/RTScheduler_include.pidl"
#include "tao/RTCORBA/RTCORBA_include.pidl"

module MIF_Scheduling
{
  local interface SegmentSchedulingParameterPolicy
  : CORBA::Policy
  {
    attribute short importance;
  };

  local interface MIF_Scheduler : RTScheduling::Scheduler
  {
    SegmentSchedulingParameterPolicy
      create_segment_scheduling_parameter
        (in short segment_importance);
  };
};
