
// -*- C++ -*-
// $Id: Version.h 96107 2012-08-29 06:17:32Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define DAnCE_MAJOR_VERSION 1
#define DAnCE_MINOR_VERSION 1
#define DAnCE_BETA_VERSION 4
#define DAnCE_VERSION "1.1.4"
