
// -*- C++ -*-
// $Id: Version.h 95964 2012-07-26 07:13:54Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define DAnCE_MAJOR_VERSION 1
#define DAnCE_MINOR_VERSION 1
#define DAnCE_BETA_VERSION 3
#define DAnCE_VERSION "1.1.3"
