
// -*- C++ -*-
// $Id: Version.h 96584 2012-12-27 09:03:02Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define DAnCE_MAJOR_VERSION 1
#define DAnCE_MINOR_VERSION 1
#define DAnCE_BETA_VERSION 7
#define DAnCE_VERSION "1.1.7"
