/**
 * @file Test.idl
 *
 * $Id: Test.idl 46427 2002-09-25 13:16:27Z jwillemsen $
 *
 * @author Carlos O'Ryan <coryan@atdesk.com>
 *
 */
#ifndef Test__idl_
#define Test__idl_

module Test
{
  typedef sequence<octet> Payload;
  interface Echo
  {
    oneway void echo_payload(in Payload data);
  };

  interface Echo_Caller
  {
    void start_task(in Echo client);

    oneway void shutdown();
  };
};

#endif /* Test__idl_ */
