// $Id: Hello_Receiver.idl 88666 2010-01-22 11:59:32Z johnnyw $

#ifndef HELLO_RECEIVER_IDL
#define HELLO_RECEIVER_IDL

#include <Components.idl>

#include "Base/Hello.idl"

module Hello
{
  component Receiver
  {
    /// Provides
    provides MyFoo do_my_foo;
  };
};
#endif
