// $Id: OneProcess_Receiver.idl 90123 2010-05-11 12:41:32Z mhengstmengel $

#ifndef ONEPROCESS_RECEIVER_IDL
#define ONEPROCESS_RECEIVER_IDL

#include <Components.idl>

#include "Base/OneProcess.idl"

module OneProcess
{
  component Receiver
  {
    /// Provides
    provides MyFoo do_my_foo;
  };
};
#endif
