// $Id: Messenger.idl 83358 2008-10-21 23:02:02Z sowayaa $

// messenger.idl

interface Messenger
{
  boolean send_message (in    string user_name,
                        in    string subject,
                        inout string message);
};

