// $Id: test.idl 46087 2002-08-22 18:11:09Z irfan $

interface A
{
  long doit();
};

module Outer
{
  interface B
    {
      long doit();
    };

  module Inner
    {
      interface C
        {
          long doit();
        };
    };
};
