// $Id: InterMulti_Receiver.idl 90307 2010-05-26 13:29:02Z mhengstmengel $

#ifndef INTERMULTI_RECEIVER_IDL
#define INTERMULTI_RECEIVER_IDL

#include <Components.idl>

#include "Base/InterMulti.idl"

module InterMulti
{
  component Receiver
  {
    /// Provides
    provides One do_my_one;
    provides Two do_my_two;
    provides Three do_my_three;
  };
};
#endif
