//
// $Id: test.idl 63647 2005-01-31 23:19:31Z mesnier_p $
//

interface Simple_Server
{
  long test_method (in long x);

  oneway void shutdown ();
};

interface Another_One
{
  long test_method (in long x);
};
