// $Id: UsesSM_Receiver.idl 90596 2010-06-15 08:16:07Z mhengstmengel $

#ifndef USESSM_RECEIVER_IDL
#define USESSM_RECEIVER_IDL

#include <Components.idl>

#include "Base/UsesSM.idl"

module UsesSM
{
  component Receiver
  {
    /// Provides
    provides One do_my_one;
    provides Two do_my_two;
  };
};
#endif
